email_template = """
<html>
  <head>
    <style>
      body {{
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
        margin: 0;
        padding: 20px;
      }}
      .container {{
        max-width: 600px;
        margin: 0 auto;
        background-color: white;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        overflow: hidden;
      }}
      .header {{
        background-color: #FFFFFF;
        color: #333;
        padding: 30px;
        text-align: center;
      }}
      .header img {{
        max-width: 150px;
        margin-bottom: 15px;
      }}
      .header h1 {{
        margin: 0;
        font-size: 24px;
      }}
      .content {{
        padding: 30px;
      }}
      .section {{
        margin-bottom: 25px;
      }}
      .section-title {{
        color: #667eea;
        font-size: 16px;
        font-weight: bold;
        border-bottom: 2px solid #667eea;
        padding-bottom: 10px;
        margin-bottom: 15px;
      }}
      .report-body {{
        color: #333;
        line-height: 1.6;
        font-size: 14px;
      }}
      .footer {{
        background-color: #f9f9f9;
        padding: 20px;
        text-align: center;
        border-top: 1px solid #ddd;
        font-size: 12px;
        color: #666;
      }}
      .info-badge {{
        display: inline-block;
        background-color: #e8f0ff;
        color: #667eea;
        padding: 10px 15px;
        border-radius: 4px;
        margin-top: 10px;
      }}
      .caution-section {{
    margin: 20px 0;
    padding: 15px;
    background-color: #fff9db; /* Amarillo muy suave */
    border-left: 5px solid #fcc419; /* Barra lateral de advertencia */
    border-radius: 4px;
    font-family: Arial, Helvetica, sans-serif;
  }}

  .info-caution {{
    color: #856404; /* Texto café oscuro para buen contraste */
    font-size: 16px;
    font-weight: bold;
    line-height: 1.5;
  }}

  .info-caution ul {{
    margin-top: 10px;
    margin-bottom: 0;
    padding-left: 20px;
    list-style-type: disc;
  }}

  .info-caution li {{
    margin-bottom: 8px;
    font-weight: normal; /* Para que el texto de los ítems sea legible */
    color: #333333;
  }}
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <img src="https://i.imgur.com/euX75qk.jpeg" alt="TerapIA Logo">
        <h1>Medical Report</h1>
        <p>TerapIA - Medical Management System</p>
      </div>
      
      <div class="content">
        <div class="section">
          <div class="section-title">Report Details</div>
          <div class="report-body">
            {body}
          </div>
        </div>
        
        <div class="section">
          <div class="info-badge">
            📋 Report automatically generated by TerapIA
          </div>
        </div>

        <div class="caution-section">
          <div class="info-caution">
            Warning Signs for Surveillance:
              {caution_signs}
          </div>
        </div>
      </div>
      
      <div class="footer">
        <p><strong>TerapIA</strong> - Medical Management System</p>
        <p>© 2026 All rights reserved | Confidential and protected</p>
        <p>This document contains confidential medical information.</p>
      </div>
    </div>
  </body>
</html>
"""
